server {
    listen 80;
    
    # server_name your_domain.com;  # Replace with your actual domain name or IP address

    location / {
        proxy_pass http://127.0.0.1:5000;  # This is the default address where Flask is running
        include /etc/nginx/proxy_params;  # Include standard proxy settings
    }

    location /static/ {
        alias /path/to/your/project/MediMind/app/static/;  # Replace with the actual path to your static files
    }

    location /uploads/ {
        alias /path/to/your/project/MediMind/uploads/;  # Replace with the actual path to file uploads
    }

    location /favicon.ico {
        alias /path/to/your/project/MediMind/app/static/favicon.ico;  # Path to your favicon
    }

    location /robots.txt {
        alias /path/to/your/project/MediMind/app/static/robots.txt;  # Path to your robots.txt file
    }

    location / {
        try_files $uri $uri/ =404;  # Handle other requests
    }
}
